# -*- coding: utf-8 -*-
"""no show model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-zKDUhiKvO8e6bSZNW7pxKlN3_bRncq
"""

df = pd.read_csv("/content/dentix_no_show_mock_data_7k.csv")

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load CSV
df = pd.read_csv("/content/dentix_no_show_mock_data_7k.csv")

# Compute total appointments and cancelled count per patient
agg = df.groupby("patientId")["status"].value_counts().unstack(fill_value=0)
agg["total_appointments"] = agg.sum(axis=1)
agg["cancelled_count"] = agg.get("Cancelled", 0)

# Compute no_show_ratio and high_risk
agg["no_show_ratio"] = agg["cancelled_count"] / agg["total_appointments"]
agg["high_risk"] = (agg["no_show_ratio"] > 0.5).astype(int)

# Prepare features and labels
X = agg[["no_show_ratio", "total_appointments"]]
y = agg["high_risk"]

# Split and train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)

print("Accuracy:", accuracy_score(y_test, model.predict(X_test)))

import joblib

joblib.dump(model, "no_show_model.pkl")

